### ISSUE TITLE
It should be easier to default to Fuel data version 1.1

### ISSUE THREAD

**Issue by dougwilson** [ExactTarget/Fuel-Node-REST#41]
Right now, in order to ensure all requests just default to the (better) Fuel data version 1.1, the only good way looks stupid:
```js
var FuelRest = require('fuel-rest');
var fuelRestClient = new FuelRest(options);

fuelRestClient.defaultHeaders['x-fueldata-version'] = '1.1';
```

I'm not sure if we should add an option explicitly for "fuelDataVersion", but at least if there was a constructor option to add to default headers, that would be a good general solution :)

**Comment by vernak2539** [comment]
sounds like a really good idea. Will work on it

**Comment by dougwilson** [comment]
Yep, looks fine to me :)
